---
age_vars_install_dir: /opt/FiloSottile/age
age_vars_version: "{{ age_version | default(bookconf.versions.age, true) }}"

age_vars:
  version: "{{ age_vars_version }}"
  dl_url: https://github.com/FiloSottile/age/releases/download/v{{ age_vars_version }}/age-v{{ age_vars_version }}-linux-{{ factum.distro.arch }}.tar.gz
  install_dir: "{{ age_vars_install_dir }}"
  bin:
    age: "{{ age_vars_install_dir }}/age"
    keygen: "{{ age_vars_install_dir }}/age-keygen"
