---
- name: Install
  ansible.builtin.package:
    name: doublecmd-{{ doublecmd_framework }}
    state: present
  become: true

- name: Deploy app autostart
  ansible.builtin.include_role: name=partial.deploy-app-autostart
  vars:
    desktop_app_autostart_file: files/doublecmd.desktop
    desktop_app_autostart_user: "{{ item }}"
  loop: "{{ doublecmd_autostarters | default([], true) }}"
  loop_control:
    label: "{{ (factum.users_obj[item] | default(item)).name }}"
