---
- name: Block
  block:
    - name: Allow install
      ansible.builtin.file: path="{{ nosnap_path }}" state=absent
      when: factum.distro.family == 'debian'

    - name: Install
      ansible.builtin.package: name=snapd state=present

    - name: Start socket
      ansible.builtin.service: name=snapd.socket enabled=yes state=started

    # fix https://exerror.com/cannot-install-code-classic-confinement-requires-snaps-under-snap-or-symlink-from-snap-to-var-lib-snapd-snap/
    - name: Apply fix
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
        force: true
      when: factum.distro.id_like | intersect(['rhel'])

    - name: Reset connection
      ansible.builtin.meta: reset_connection
  vars:
    nosnap_path: path=/etc/apt/preferences.d/nosnap.pref
    id_unlike_options: ['rhel']
  become: true
  when:
    - factum.distro.id_like | intersect(id_unlike_options) | length < 1
