---
- name: Install
  ansible.builtin.package: name=epel-release state=present
  register: repo_epel_installation_result
  become: true
  vars:
    id_like_options: ['rhel']
  when: factum.distro.id_like | intersect(id_like_options) | length > 0

- name: Register installation result
  ansible.builtin.set_fact:
    repo_epel_state_changed: "{{ repo_epel_installation_result.changed | default(false) }}"
