---
- name: Block
  block:
    - name: Create keyring directory (repo={{ repo_name }})
      ansible.builtin.file:
        path: "{{ keyring | dirname }}"
        state: directory
        mode: '0755'

    - name: Install GPG key (repo={{ repo_name }})
      ansible.builtin.apt_key:
        url: "{{ item }}"
        keyring: "{{ keyring }}"
        state: present
      loop: "{{ keys }}"

    - name: Add source (repo={{ repo_name }})
      ansible.builtin.copy:
        content: "{{ repos | default([], true) | join('\n') }}{{ '\n' }}"
        dest: /etc/apt/sources.list.d/{{ repo_name }}.list
        mode: '0644'
      register: repo_add_ppa_result

    - name: Update cache (repo={{ repo_name }})
      ansible.builtin.package: update_cache=yes
      when: repo_add_ppa_result.changed
  become: true

- name: Register installation result (repo={{ repo_name }})
  ansible.builtin.set_fact:
    "repo_{{ repo_name }}_state_changed": "{{ repo_add_ppa_result.changed }}"
