---
- name: Install
  ansible.builtin.include_tasks: inc/install-{{ id_like }}.yml
  vars:
    id_like_options: ['rhel']
    id_like: "{{ factum.distro.id_like | intersect(id_like_options) | first | default(false, true) }}"
  when: id_like

- name: Register installation result
  ansible.builtin.set_fact:
    repo_remi_state_changed: "{{ repo_remi_add_result.changed | default(false) }}"
