---
- name: Block
  block:
    - name: Create keyring directory
      ansible.builtin.file:
        path: "{{ keyring | dirname }}"
        state: directory
        mode: '0755'

    - name: Install GPG key
      ansible.builtin.apt_key:
        url: "{{ item }}"
        keyring: "{{ keyring }}"
        state: present
      loop: "{{ keys }}"

    - name: Add source
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        filename: nodejs
        update_cache: true
      register: repo_nodejs_add_result
      loop: "{{ repos }}"
      vars:
  vars:
    keys:
      - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/keyrings/nodejs.gpg
    codename: "{{ factum.distro.ubuntu_codename }}"
    version: "{{ bookconf.versions.nodejs }}"
    repos:
      - deb [signed-by={{ keyring }}] https://deb.nodesource.com/node_{{ version }}.x {{ codename }} main
      - deb-src [signed-by={{ keyring }}] https://deb.nodesource.com/node_{{ version }}.x {{ codename }} main
  become: true
