---
- name: Add repo
  ansible.builtin.include_role: name=repo-add-ppa
  vars:
    repo_name: et
    keyring: /etc/apt/keyrings/{{ repo_name }}.gpg
    keys:
      - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xd3614cb0b3c2d154356bd436cb4adea5b72a07a1
    codename: "{{ factum.distro.ubuntu_codename }}"
    repos:
      - deb [signed-by={{ keyring }}] https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu {{ codename }} main
      - deb-src [signed-by={{ keyring }}] https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu {{ codename }} main
    # Determine if the role should be included
    id_like_options: ['debian']
    id_like: "{{ factum.distro.id_like | intersect(id_like_options) | first | default(false, true) }}"
  when: id_like
