---
- name: Add repo
  ansible.builtin.include_role: name=partial.add-ppa
  vars:
    codename: "{{ factum.distro.ubuntu_codename }}"
    # add_ppa vars
    add_ppa_repo_name: et
    add_ppa_keyring: /etc/apt/keyrings/{{ add_ppa_repo_name }}.gpg
    add_ppa_keys:
      - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xd3614cb0b3c2d154356bd436cb4adea5b72a07a1
    add_ppa_repos:
      - deb [signed-by={{ add_ppa_keyring }}] https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu {{ codename }} main
      - deb-src [signed-by={{ add_ppa_keyring }}] https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu {{ codename }} main
