---
- name: Install
  ansible.builtin.package: name="{{ pkgs }}" state="{{ pkg_state }}"
  become: true
  vars:
    pkgs: ['nodejs']
    pkg_state: "{{ repo_nodejs_state_changed | default(false) | ternary('latest', 'present') }}"
