---
- name: Install
  ansible.builtin.package: name="{{ pkgs }}" state="{{ nodejs_pkg_state }}"
  become: true
  vars:
    pkgs: ['nodejs']
    repo_changed: repo_nodejs_state_changed | default(false)
    nodejs_pkg_state: "{{ repo_changed | ternary('latest', 'present') }}"
