---
- name: Add repo
  ansible.builtin.include_role: name=partial.add-ppa
  vars:
    codename: "{{ factum.distro.ubuntu_codename }}"
    # add_ppa vars
    add_ppa_repo_name: kdenlive
    add_ppa_keyring: /etc/apt/keyrings/{{ add_ppa_repo_name }}.gpg
    add_ppa_keys:
      - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa59e5ebfccc61564d6d4365b2763b0ee7709fe97
    add_ppa_repos:
      - deb [signed-by={{ add_ppa_keyring }}] https://ppa.launchpadcontent.net/kdenlive/kdenlive-stable/ubuntu {{ codename }} main
      - deb-src [signed-by={{ add_ppa_keyring }}] https://ppa.launchpadcontent.net/kdenlive/kdenlive-stable/ubuntu {{ codename }} main
