---
- name: Install
  ansible.builtin.package: name="{{ pkgs }}" state=present
  vars:
    default_pkgs: ['lm_sensors']
    id_like_to_pkgs:
      debian: ['lm-sensors']
    id_like: "{{ factum.distro.id_like | intersect(id_like_to_pkgs.keys()) | first | default('_') }}"
    pkgs: "{{ id_like_to_pkgs[id_like] | default(default_pkgs, true) }}"
  become: true
