---
- name: Age
  block:
    - name: Check current version
      ansible.builtin.shell:
        cmd: "{{ bin.age | quote }} --version | head -1"
      args:
        executable: /usr/bin/bash
      register: age_installed_version
      failed_when: false
      changed_when: false

    - name: Tool
      ansible.builtin.include_tasks: inc/install.yml
      when: age_installed_version.stdout.find(version) | int == -1

    - name: Deploy shell hook
      ansible.builtin.include_role: name=partial-deploy-shell-hook
      vars:
        shell_hook_dest_dir: "{{ install_dir }}"
        shell_hook_bin_dir: "{{ bin_dir }}"
        shell_hook_symlink_dest: "{{ envar_vars.sys_initd }}/{{ bookconf.priority.age | default(bookconf.priority._default, true) }}-age.sh"
  become: true
  vars:
    install_dir: /opt/FiloSottile/age
    bin_dir: "{{ install_dir }}/bin"
    bin:
      age: "{{ bin_dir }}/age"
      age-keygen: "{{ bin_dir }}/age-keygen"
    version: "{{ age_version | default(bookconf.versions.age, true) }}"
    dl_url: https://github.com/FiloSottile/age/releases/download/v{{ version }}/age-v{{ version }}-{{ ansible_system | lower }}-{{ factum.distro.arch }}.tar.gz
