---
- name: Install
  ansible.builtin.package: name="{{ pkgs }}" state="{{ pkg_state }}"
  vars:
    pkgs: ['copyq']
    repo_changed: "{{ (repo_copyq_state_changed | default(false)) }}"
    pkg_state: "{{ repo_changed | ternary('latest', 'present') }}"
  become: true

- name: Deploy app autostart
  ansible.builtin.include_role: name=partial.deploy-app-autostart
  vars:
    desktop_app_autostart_file: files/copyq.desktop
    desktop_app_autostart_user: "{{ item }}"
  loop: "{{ copyq_autostarters | default([], true) }}"
  loop_control:
    label: "{{ (factum.users_obj[item] | default(item)).name }}"
