---
- name: Install
  ansible.builtin.package: name="{{ pkgs }}" state="{{ pkg_state }}"
  vars:
    pkgs:
      - mkvtoolnix
      - mkvtoolnix-gui
    repo_changed: "{{ (repo_mkvtoolnix_state_changed | default(false)) }}"
    pkg_state: "{{ repo_changed | ternary('latest', 'present') }}"
  become: true
