---
# from here:
# * https://deb.nodesource.com/setup_18.x
# * https://rpm.nodesource.com/setup_18.x
- name: Block
  block:
    - name: Add repo
      ansible.builtin.include_role: name=repo-add-ppa
      vars:
        repo_name: nodejs
        keyring: /etc/apt/keyrings/{{ repo_name }}.gpg
        keys:
          - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        codename: "{{ factum.distro.ubuntu_codename }}"
        repos:
          - deb [signed-by={{ keyring }}] https://deb.nodesource.com/node_{{ version }}.x {{ codename }} main
          - deb-src [signed-by={{ keyring }}] https://deb.nodesource.com/node_{{ version }}.x {{ codename }} main
        # Determine if the role should be included
        id_like_options: ['debian']
        id_like: "{{ factum.distro.id_like | intersect(id_like_options) | first | default(false, true) }}"
      when: id_like

    - name: Add repo
      ansible.builtin.include_tasks: inc/install-{{ id_like }}.yml
      vars:
        id_like_options: ['rhel']
        id_like: "{{ factum.distro.id_like | intersect(id_like_options) | first | default(false, true) }}"
      when: id_like
  vars:
    version: "{{ nodejs_version | default(bookconf.versions.nodejs, true) }}"
