---
- name: Add repo
  ansible.builtin.include_role: name=partial.add-ppa
  vars:
    arch: "{{ factum.distro.arch }}"
    # add_ppa vars
    add_ppa_repo_name: brave
    add_ppa_keyring: /etc/apt/keyrings/{{ add_ppa_repo_name }}.gpg
    add_ppa_keys:
      - https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    add_ppa_repos:
      - deb [signed-by={{ add_ppa_keyring }} arch={{ arch }}] https://brave-browser-apt-release.s3.brave.com/ stable main
