---
- name: Block
  block:
    - name: Install repo
      ansible.builtin.template:
        src: nodesource.repo.j2
        dest: /etc/yum.repos.d/nodesource.repo
        force: true
        mode: 0644
      vars:
        dist_major_version: "{{ factum.distro.major_version }}"
      register: repo_nodejs_add_result

    - name: Disable appstream module
      ansible.builtin.command: dnf module disable -y nodejs
      register: repo_nodejs_appstream_disable_result
      changed_when: "'Nothing to do.' not in repo_nodejs_appstream_disable_result.stdout_lines"
  become: true

- name: Register installation result
  ansible.builtin.set_fact:
    repo_nodejs_state_changed: "{{ repo_nodejs_add_result.changed }}"
