---
all:
  # demo vars to pass
  vars:
    ansible_host: "{{ inventory_hostname }}.local"
  hosts:
    # demo1 machine configuration sample
    demo1:
      ansible_host: PLACEHOLDER
      ansible_user: PLACEHOLDER
      ansible_password: "{{ lookup('file', 'resources/secrets/becomer/demo1.pass') }}"
      ansible_become_password: "{{ lookup('file', 'resources/secrets/becomer/demo1.pass') }}"
      ansible_become_method: sudo
    # demo2 machine configuration sample
    # ansible_hostname from vars will be used
    demo2:
      ansible_user: PLACEHOLDER
      ansible_password: "{{ lookup('file', 'resources/secrets/becomer/demo1.pass') }}"
      ansible_become_password: "{{ lookup('file', 'resources/secrets/becomer/demo1.pass') }}"
      ansible_become_method: sudo
  children:
    # group1 group sample
    group1:
      hosts:
        demo1:
    # demos group sample
    demos:
      children:
        group1:
      hosts:
        demo2:
