---
all:
  vars:
    ansible_host: "{{ inventory_hostname }}.local"
    ansible_user: "{{ lookup('env', 'HOSTS_USER') }}"
    # passwords better to be loaded from vaulted file
    # "{{ lookup('file', 'resources/secrets/becomer/demo1.pass') }}"
    ansible_password: "{{ lookup('env', 'HOSTS_USER_PASS') }}"
    ansible_become_password: "{{ lookup('env', 'HOSTS_USER_PASS') }}"
    ansible_become_method: sudo
  hosts:
    almalinux:
      ansible_host: "{{ lookup('env', 'HOST_ALMALINUX') }}"
    debian:
      ansible_host: "{{ lookup('env', 'HOST_DEBIAN') }}"
    mint:
      ansible_host: "{{ lookup('env', 'HOST_MINT') }}"
    ubuntu:
      ansible_host: "{{ lookup('env', 'HOST_UBUNTU') }}"
  children:
    # group1 group sample
    servers:
      hosts:
        almalinux:
        debian:
        ubuntu:
    # demos group sample
    home:
      children:
        servers:
      hosts:
        mint:
