---
- name: Block
  block:
    - name: Create etc docker directory
      ansible.builtin.file:
        path: "{{ daemon_json_path | dirname }}"
        state: directory
        mode: '0755'

    - name: Check daemon config exists
      ansible.builtin.stat: path="{{ daemon_json_path }}"
      register: docker_daemon_json_file

    - name: Create daemon config file
      ansible.builtin.copy:
        src: daemon.json
        dest: "{{ daemon_json_path }}"
        mode: "{{ docker_vars.daemon_json_file_mode }}"
      when: not docker_daemon_json_file.stat.exists

    - name: Load daemon config
      ansible.builtin.slurp: src="{{ daemon_json_path }}"
      register: docker_daemon_file
  vars:
    daemon_json_path: "{{ docker_vars.daemon_json_path }}"
  become: true

- name: Convert daemon config to obj
  ansible.builtin.set_fact:
    docker_daemon_json: "{{ docker_daemon_file.content | b64decode | from_json }}"

- ansible.builtin.include_tasks: file=daemon/registries.yml
