---
# https://tmuxp.git-pull.com/configuration/examples.html
# https://leanpub.com/the-tao-of-tmux/read#window-layouts
#
# See readme.md for configuration demo
# https://github.com/varlogerr/ansible-base/blob/master/tmux/core/roles/tmuxp/readme.md
tmuxp_users_confs: []
