---
- name: Add repo
  ansible.builtin.include_role: name=partial.add-ppa
  vars:
    arch: "{{ factum.distro.arch }}"
    codename: "{{ factum.distro.ubuntu_codename }}"
    # add_ppa vars
    add_ppa_repo_name: mkvtoolnix
    add_ppa_keyring: /etc/apt/keyrings/{{ add_ppa_repo_name }}.gpg
    add_ppa_keys:
      - https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt
    add_ppa_repos:
      - deb [signed-by={{ add_ppa_keyring }} arch={{ arch }}] https://mkvtoolnix.download/ubuntu/ {{ codename }} main
      - deb-src [signed-by={{ add_ppa_keyring }} arch={{ arch }}] https://mkvtoolnix.download/ubuntu/ {{ codename }} main
