---
- name: Block
  block:
    - name: Create keyring directory
      ansible.builtin.file:
        path: "{{ keyring | dirname }}"
        state: directory
        mode: '0755'

    - name: Install GPG key
      ansible.builtin.apt_key:
        url: "{{ item }}"
        keyring: "{{ keyring }}"
        state: present
      loop: "{{ keys }}"

    - name: Add source
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        filename: docker
        update_cache: true
      register: repo_docker_add_result
      loop: "{{ repos }}"
      vars:
  vars:
    repo_dist_id: "{{ (factum.distro.id_like | intersect(['ubuntu']) | length > 0) | ternary('ubuntu', 'debian') }}"
    keys:
      - https://download.docker.com/linux/{{ repo_dist_id }}/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    codename: "{{ (repo_dist_id in ['ubuntu']) | ternary(factum.distro.ubuntu_codename, factum.distro.codename) }}"
    arch: "{{ factum.distro.arch }}"
    repos:
      - deb [signed-by={{ keyring }} arch={{ arch }}] https://download.docker.com/linux/{{ repo_dist_id }} {{ codename }} stable
  become: true
