---
- name: Add repo
  ansible.builtin.include_role: name=partial.add-ppa
  vars:
    # add_ppa vars
    add_ppa_repo_name: sublime
    add_ppa_keyring: /etc/apt/keyrings/{{ add_ppa_repo_name }}.gpg
    add_ppa_keys:
      - https://download.sublimetext.com/sublimehq-pub.gpg
    add_ppa_repos:
      - deb [signed-by={{ add_ppa_keyring }}] https://download.sublimetext.com/ apt/stable/
