---
- name: Install
  ansible.builtin.package: name="{{ pkgs }}" state=present
  become: true
  vars:
    pkgs: ['gpg']
    id_like_options: ['debian']
  when:
    - factum.distro.id_like | intersect(id_like_options) | length > 0
