---
- name: Block
  block:
      # Fixes missing libprotobuf-lite17 package:
      #   https://github.com/MisterTea/EternalTerminal/issues/437
    - name: Install libprotobuf-lite17
      ansible.builtin.apt: deb="{{ pkg_url }}"
      vars:
        pkg_url: http://ftp.us.debian.org/debian/pool/main/p/protobuf/libprotobuf-lite17_3.6.1.3-2_amd64.deb
      when:
        - factum.distro.id in ['debian']

    - name: Install
      ansible.builtin.package: name="{{ pkgs }}" state="{{ pkg_state }}"
      register: et_installation_state
      become: true
      vars:
        pkgs: ['et']
        repo_changed: "{{
            (repo_et_state_changed | default(false))
            or (repo_remi_state_changed | default(false))
          }}"
        pkg_state: "{{ repo_changed | ternary('latest', 'present') }}"

    - name: Start et service
      ansible.builtin.service: name={{ et_vars.service }} state=started enabled=yes
      register: et_service_state

    - name: Expose ports (firewalld)
      ansible.posix.firewalld:
        port: "{{ port }}"
        state: enabled
        permanent: true
        immediate: true
        offline: true
      loop: "{{ ports }}"
      loop_control:
        loop_var: port
      when: (ansible_facts.services['firewalld.service'].state | default('')) == 'running'

    - name: Expose ports (ufw)
      community.general.ufw:
        rule: allow
        port: "{{ port.split('/') | first }}"
        proto: "{{ port.split('/') | last }}"
      loop: "{{ ports }}"
      loop_control:
        loop_var: port
      when: (ansible_facts.services['ufw.service'].state | default('')) == 'running'
  become: true
  vars:
    ports:
      - 2022/tcp

- name: Reload services facts
  ansible.builtin.service_facts:
  when: >
    (et_installation_state.changed | default(False))
    or (et_service_state.changed | default(False))
