---
- name: Install
  community.general.snap: name=teams-for-linux state=present
  become: true
  when:
    - factum.distro.id_like | intersect(snapd_vars.id_unlike_options) | length < 1

- name: Deploy app autostart
  ansible.builtin.include_role: name=partial.deploy-app-autostart
  vars:
    desktop_app_autostart_file: files/teams.desktop
    desktop_app_autostart_user: "{{ item }}"
  loop: "{{ teams_autostarters | default([], true) }}"
  loop_control:
    label: "{{ (factum.users_obj[item] | default(item)).name }}"
