---
- name: Configuration
  block:
    - name: Create configuration directory
      ansible.builtin.file:
        path: "{{ mpv_confpath | dirname }}"
        state: directory
        mode: '0755'

    - name: Apply file configuration
      ansible.builtin.copy:
        src: "{{ mpv_conffile.src }}"
        dest: "{{ mpv_confpath }}"
        mode: 0644

    - name: Apply template configuration
      ansible.builtin.template:
        src: "{{ mpv_conffile.src }}"
        dest: "{{ mpv_confpath }}"
        mode: 0644
      vars:
        tpl_vars: "{{ mpv_conffile.tpl_vars }}"
  vars:
    mpv_confpath: /etc/mpv/mpv.conf
  become: true
