---
- name: Tmuxp
  block:
    - name: Install
      ansible.builtin.package: name=tmuxp state=present
      when: factum.distro.id_like | intersect(pip_id_like_options) | length < 1
      become: true

    - name: Install with pip
      ansible.builtin.include_role: name=pip-tmuxp
      when: factum.distro.id_like | intersect(pip_id_like_options) | length > 0
  vars:
    pip_id_like_options: ['rhel']
