---
- name: Install
  ansible.builtin.package: name=tmuxp state=present
  become: true
  vars:
    id_like_options: ['debian']
  when:
    - factum.distro.id_like | intersect(id_like_options) | length > 0
